/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedToolsResearchRouteImport } from './routes/_authenticated/tools.research'
import { Route as AuthenticatedToolsPlannerRouteImport } from './routes/_authenticated/tools.planner'
import { Route as AuthenticatedToolsMeetingRouteImport } from './routes/_authenticated/tools.meeting'
import { Route as AuthenticatedToolsEmailRouteImport } from './routes/_authenticated/tools.email'
import { Route as AuthenticatedToolsChatRouteImport } from './routes/_authenticated/tools.chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsResearchRoute =
  AuthenticatedToolsResearchRouteImport.update({
    id: '/tools/research',
    path: '/tools/research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsPlannerRoute =
  AuthenticatedToolsPlannerRouteImport.update({
    id: '/tools/planner',
    path: '/tools/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsMeetingRoute =
  AuthenticatedToolsMeetingRouteImport.update({
    id: '/tools/meeting',
    path: '/tools/meeting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsEmailRoute = AuthenticatedToolsEmailRouteImport.update({
  id: '/tools/email',
  path: '/tools/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsChatRoute = AuthenticatedToolsChatRouteImport.update({
  id: '/tools/chat',
  path: '/tools/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/tools/chat': typeof AuthenticatedToolsChatRoute
  '/tools/email': typeof AuthenticatedToolsEmailRoute
  '/tools/meeting': typeof AuthenticatedToolsMeetingRoute
  '/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/tools/research': typeof AuthenticatedToolsResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/tools/chat': typeof AuthenticatedToolsChatRoute
  '/tools/email': typeof AuthenticatedToolsEmailRoute
  '/tools/meeting': typeof AuthenticatedToolsMeetingRoute
  '/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/tools/research': typeof AuthenticatedToolsResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/tools/chat': typeof AuthenticatedToolsChatRoute
  '/_authenticated/tools/email': typeof AuthenticatedToolsEmailRoute
  '/_authenticated/tools/meeting': typeof AuthenticatedToolsMeetingRoute
  '/_authenticated/tools/planner': typeof AuthenticatedToolsPlannerRoute
  '/_authenticated/tools/research': typeof AuthenticatedToolsResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/api/chat'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/meeting'
    | '/tools/planner'
    | '/tools/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/api/chat'
    | '/tools/chat'
    | '/tools/email'
    | '/tools/meeting'
    | '/tools/planner'
    | '/tools/research'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/tools/chat'
    | '/_authenticated/tools/email'
    | '/_authenticated/tools/meeting'
    | '/_authenticated/tools/planner'
    | '/_authenticated/tools/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/research': {
      id: '/_authenticated/tools/research'
      path: '/tools/research'
      fullPath: '/tools/research'
      preLoaderRoute: typeof AuthenticatedToolsResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/planner': {
      id: '/_authenticated/tools/planner'
      path: '/tools/planner'
      fullPath: '/tools/planner'
      preLoaderRoute: typeof AuthenticatedToolsPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/meeting': {
      id: '/_authenticated/tools/meeting'
      path: '/tools/meeting'
      fullPath: '/tools/meeting'
      preLoaderRoute: typeof AuthenticatedToolsMeetingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/email': {
      id: '/_authenticated/tools/email'
      path: '/tools/email'
      fullPath: '/tools/email'
      preLoaderRoute: typeof AuthenticatedToolsEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/chat': {
      id: '/_authenticated/tools/chat'
      path: '/tools/chat'
      fullPath: '/tools/chat'
      preLoaderRoute: typeof AuthenticatedToolsChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsChatRoute: typeof AuthenticatedToolsChatRoute
  AuthenticatedToolsEmailRoute: typeof AuthenticatedToolsEmailRoute
  AuthenticatedToolsMeetingRoute: typeof AuthenticatedToolsMeetingRoute
  AuthenticatedToolsPlannerRoute: typeof AuthenticatedToolsPlannerRoute
  AuthenticatedToolsResearchRoute: typeof AuthenticatedToolsResearchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsChatRoute: AuthenticatedToolsChatRoute,
  AuthenticatedToolsEmailRoute: AuthenticatedToolsEmailRoute,
  AuthenticatedToolsMeetingRoute: AuthenticatedToolsMeetingRoute,
  AuthenticatedToolsPlannerRoute: AuthenticatedToolsPlannerRoute,
  AuthenticatedToolsResearchRoute: AuthenticatedToolsResearchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
